#
# Copyright (c) 2024 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_LOG=y
CONFIG_GPIO=y
CONFIG_SPI=y
# STEP 1 - Enable nrfx drivers #
# Right names for low-level peripheral drivers
#CONFIG_ADC=y
CONFIG_NRFX_SAADC=y
CONFIG_NRFX_TIMER=y
CONFIG_NRFX_GPPI=y
# enable spi and other???
#CONFIG_CBPRINTF_FP_SUPPORT=y
#CONFIG_RESET_ON_FATAL_ERROR=n
#CONFIG_HEAP_MEM_POOL_SIZE=8192
#CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
#CONFIG_MAIN_STACK_SIZE=4096
#CONFIG_THREAD_NAME=y
#CONFIG_BT_RX_STACK_SIZE=2048
# STEP 1.1 - Enable Kconfigs for SPI and GPIO
#CONFIG_GPIO=y
#CONFIG_SPI=y
